version: "3"
services:
  nginx:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      dockerfile: Dockerfile_nginx
    ports: 
      - "3456:80"
      - "443:443"
    networks:
      - internal
    volumes:
      - ./src/laravel/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    # image: php:8.1-fpm-alpine
    build:
      context: .
      dockerfile: Dockerfile_php
    networks:
      - internal
    volumes:
      - ./src/laravel/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
networks:
  internal:
    driver: bridge