version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3456:80"
      - "443:443"
    networks:
      - internal
    volumes:
      - ./src/laravel/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  php:
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
      - ./src/laravel/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
networks:
  internal:
    driver: bridge